name: test-ecosystem

on:
  push:
    branches: main
  pull_request:
    branches: main

permissions:
  contents: read

jobs:
  test-ecosystem:
    runs-on: ubuntu-latest
    steps:
      - name: checkout main repo
        uses: actions/checkout@v4
        with:
          repository: "neurosnap/starfx"
          path: "starfx"
      - name: checkout example repo
        uses: actions/checkout@v4
        with:
          repository: "neurosnap/starfx-examples"
          path: "starfx-examples"

      - run: ls

      - name: setup deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - name: npm
        run: deno task npm 0.0.0
        working-directory: starfx

      # install in example repos
      - name: install vite-react
        working-directory: starfx-examples/vite-react
        run: |
          corepack enable
          yarn install

      # symlink example repos
      - name: symlink built assets
        run: deno task sync-build-to starfx-examples/vite-react
        working-directory: starfx

      # run build and test in example repos
      - name: build vite-react
        working-directory: starfx-examples/vite-react
        run: yarn build
