name: test-ecosystem

on:
  push:
    branches: main
  pull_request:
    branches: main

permissions:
  contents: read

jobs:
  test-ecosystem:
    name: ${{ matrix.example }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        example:
          - starfx-examples/vite-react
          - starfx-examples/parcel-react

    steps:
      - name: checkout main repo
        uses: actions/checkout@v4
        with:
          repository: "neurosnap/starfx"
          path: "starfx"
      - name: checkout example repo
        uses: actions/checkout@v4
        with:
          repository: "neurosnap/starfx-examples"
          path: "starfx-examples"

      - name: setup deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - name: npm
        run: deno task npm 0.0.0
        working-directory: starfx

      # install in example repos
      - name: install ${{ matrix.example }}
        working-directory: ${{ matrix.example }}
        run: npm install

      # symlink example repos
      - name: symlink built assets
        run: deno task sync-build-to ${{ matrix.example }}
        working-directory: starfx

      # run build and test in example repos
      - name: build ${{ matrix.example }}
        working-directory: ${{ matrix.example }}
        run: npm run build
